[project]
name = "viu"
version = "0.1.0"
description = ""
authors = [
    {name = "ducdetronquito",email = "guillaume.paulet@giome.fr"}
]
requires-python = ">=3.14"
dependencies = [
    "django (>=5.2.0,<7.0.0)",
    "pydantic (>=2.0.0,<3.0.0)",
]

[dependency-groups]
test = [
    "pytest-django (>=4.12.0,<5.0.0)",
]
ci = [
    "pytest-github-actions-annotate-failures (>=0.4.0,<0.5.0)"
]
tools = [
    "django-types (>=0.24.0,<1.0.0)",
    "prek (>=0.3.13,<0.4.0)",
    "pyrefly (>=1.0.0,<2.0.0)",
    "ruff (>=0.15.12,<1.0.0)",
]

[tool.poetry.group.ci]
optional = true


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
addopts = [
    "--import-mode=importlib"
]

[tool.ruff]
line-length = 120

[tool.pyrefly]
project-includes = ["viu", "tests"]
search-path = ["viu"]
infer-with-first-use = true
min-severity = "info"
preset = "strict"
